# Generated by Django 4.2.3 on 2023-08-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Attribute Description')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Element')),
            ],
        ),
        migrations.CreateModel(
            name='Orbment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('power', models.CharField(blank=True, max_length=5, null=True, verbose_name='Power')),
                ('range', models.CharField(blank=True, max_length=20, null=True, verbose_name='Range')),
                ('sepith_cost', models.IntegerField(blank=True, null=True, verbose_name='Sepith Cost')),
                ('u_material_cost', models.IntegerField(blank=True, null=True, verbose_name='U-Material Cost')),
                ('slots_required', models.IntegerField(default=1, verbose_name='Number of Slots Required')),
                ('attribute_type', models.ManyToManyField(to='orbment_list.attribute')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbment_list.element', verbose_name='Element')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbment_list.attributetype', verbose_name='Attribute Type'),
        ),
    ]
