# Generated by Django 4.2.3 on 2023-08-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbment_list', '0003_power_range_alter_orbment_power_alter_orbment_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
