# Generated by Django 4.2.3 on 2023-08-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbment_list', '0005_rename_attribute_type_orbment_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, null=True, verbose_name='Attirbute Value')),
            ],
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.ManyToManyField(to='orbment_list.attributevalue'),
        ),
    ]
