# Generated by Django 4.2.3 on 2023-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbment_list', '0006_attributevalue_rename_attribute_name_attribute_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(default=22, max_length=10, verbose_name='Attribute Value'),
            preserve_default=False,
        ),
    ]
