# Generated by Django 4.2.3 on 2023-08-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbment_list', '0007_remove_attribute_value_delete_attributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='orbment',
            options={'ordering': ['element', 'name']},
        ),
        migrations.AlterField(
            model_name='orbment',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='orbment_list.attribute'),
        ),
    ]
