# Generated by Django 4.2.3 on 2023-08-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbment_list', '0008_alter_attribute_options_alter_orbment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbment',
            name='slots_required',
            field=models.IntegerField(default=0, verbose_name='Number of Slots Required'),
        ),
    ]
